### ISSUE TITLE
Project-agnostic components (files)

### ISSUE THREAD

**Issue by Xeizzen** [qbeon/service-modelling-language#17]
currently we're tightly binding a file to the schema using the service model namespace in the file declaration:
```
entity ProjectNamespace::Person

properties {
    firstName String
    lastName  String
}
```
Is this really necessary? Can't we just remove the tight coupling to let the file be easily reused in multiple projects?

**Comment by romshark** [comment]
@Xeizzen reusing a file in a different project is actually straightforward, you just copy it and change the schema namespace, that's it. It's tightly bound to prevent files from accidentally being moved between schemas. Also, if we allow defining sub-types in the future as describe in [here](https://github.com/qbeon/service-modelling-language/issues/12#issuecomment-457847538) then the risk of moving types between folders becomes even higher, thus it's better to be prepared since it's not that much of an overhead anyway.
